"""compiler/appgen.py — § B6 App-gen surface v1 (D43): describe an idea, get a real
running website with its own database, watched live via a real sandbox preview URL.

Scoped-down v1 (founder-confirmed, s39): ONE fixed real Next.js starter template
(proving the real infra chain works), not yet the full "rewrite until it matches what
you described" loop -- that's the next phase, reusing codeact/swe_loop.py's already-
built iterate-until-green pattern. Uses the REAL cloud E2B sandbox (already wired,
tools/sandbox.py) and a REAL per-app Postgres database on the existing shared
madras-postgres server -- not self-hosted E2B/Supabase yet (that's the later
cost-optimization D43 logs for scale, not a launch blocker).
"""

from __future__ import annotations

import re
import secrets
from dataclasses import dataclass, field

import asyncpg

from madras.config import settings
from madras.tools.sandbox import Sandbox, build_sandbox

_APP_PORT = 3000

# A deliberately minimal, real Next.js app -- enough to install, run, and be reachable.
_STARTER_FILES: dict[str, str] = {
    "package.json": (
        '{"name":"generated-app","version":"0.1.0","private":true,'
        '"scripts":{"dev":"next dev -p 3000"},'
        '"dependencies":{"next":"14.2.5","react":"18.3.1","react-dom":"18.3.1"}}'
    ),
    "app/page.tsx": (
        "export default function Page() {\n"
        "  return <main style={{fontFamily:'monospace',padding:'3rem'}}>"
        "<h1>Your app is alive.</h1>"
        "<p>Generated by Madras -- this is the real starter, running for real.</p>"
        "</main>;\n"
        "}\n"
    ),
    "app/layout.tsx": (
        "export default function RootLayout({ children }: { children: React.ReactNode }) {\n"
        "  return <html><body>{children}</body></html>;\n"
        "}\n"
    ),
    "next.config.js": "module.exports = {};\n",
}


def slugify_app_name(outcome: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", outcome.lower()).strip("_")[:40] or "app"
    return f"appgen_{slug}_{secrets.token_hex(3)}"


@dataclass
class AppGenResult:
    app_name: str
    status: str  # "provisioning" | "installing" | "starting" | "ready" | "error"
    preview_url: str | None = None
    database_name: str | None = None
    error: str | None = None
    log: list[str] = field(default_factory=list[str])


async def provision_database(app_name: str) -> str:
    """Create a real, separate Postgres database for this one generated app on the
    existing shared server -- not a new server, just a new database on it. Returns the
    database name (not a full DSN with credentials, kept out of API responses)."""
    # `admin_url`, NOT `postgres_url`. Since D83 the application connects as the DDL-less
    # `madras_app` role so RLS policies actually apply to it -- which means it cannot CREATE
    # DATABASE, and this call fails with InsufficientPrivilegeError. The variable was always
    # called admin_conn; it was the value that drifted when the roles were split. `admin_url`
    # falls back to `postgres_url` when MADRAS_POSTGRES_ADMIN_URL is unset, so a database that
    # was never split keeps working.
    admin_conn = await asyncpg.connect(dsn=settings.admin_url)
    try:
        db_name = app_name  # already slug-safe from slugify_app_name
        await admin_conn.execute(f'CREATE DATABASE "{db_name}"')
        return db_name
    finally:
        await admin_conn.close()


async def generate_app(
    *, outcome: str, app_name: str | None = None, sandbox: Sandbox | None = None
) -> AppGenResult:
    """Runs the real v1 chain: scaffold the fixed starter into a sandbox, install deps,
    start the dev server, get a real public preview URL, provision a real database.

    `app_name` should be pre-derived (via `slugify_app_name`) and passed in whenever the
    caller needs to know the job's identity BEFORE this coroutine finishes (e.g. to poll
    it) -- slugify_app_name has a random suffix, so calling it again here would silently
    diverge from a name the caller already committed to."""
    app_name = app_name or slugify_app_name(outcome)
    result = AppGenResult(app_name=app_name, status="provisioning")
    sbx = sandbox or build_sandbox(session_id=app_name, backend="e2b")

    try:
        await sbx.start()
        result.log.append("sandbox started")

        for path, content in _STARTER_FILES.items():
            write_res = await sbx.write_file(path, content)
            if not write_res.ok:
                result.status = "error"
                result.error = f"failed writing {path}: {write_res.error}"
                return result
        result.log.append("starter template written")

        result.status = "installing"
        install_res = await sbx.run_command("npm install", timeout=180)
        if not install_res.ok:
            result.status = "error"
            result.error = f"npm install failed: {install_res.stderr or install_res.error}"
            return result
        result.log.append("dependencies installed")

        result.status = "starting"
        await sbx.start_background("npm run dev")
        result.log.append("dev server starting")

        preview = await sbx.preview_url(_APP_PORT)
        if preview is None:
            result.status = "error"
            result.error = "sandbox backend doesn't support a public preview URL"
            return result

        db_name = await provision_database(app_name)
        result.database_name = db_name
        result.log.append(f"database '{db_name}' provisioned")

        result.preview_url = preview
        result.status = "ready"
        return result
    except Exception as exc:  # a real infra failure (E2B/Postgres down) -- surface, don't swallow
        result.status = "error"
        result.error = f"{type(exc).__name__}: {exc}"
        return result
